{
    "code": 0,
    "message": "",
    "data": {
        "apply_id": -1,
        "position_id": 0,
        "position_type": "qiye",
        "position_title": "周末雀巢详情发传单",
        "company_name": "雀巢食品有限公司",
        "company_id": 1,
        "job_category": "兼职招聘-传单派发",
        "work_time": "5,6,7",
        "work_date_start": "2015-07-04",
        "work_date_end": "2015-08-04",
        "recruit_num": 150,
        "salary": 200,
        "salary_unit": "天",
        "work_location": "中钢国际大厦5层",
        "work_province": "北京",
        "work_city": "北京",
        "work_district": "海淀区",
        "position_descriptin": "主要负责雀巢系列饮品在超市的销售、活动",
        "gender": 1,
        "min_age": 20,
        "max_age": 30,
        "degree": 2,
        "height": 160,
        "work_years": 1,
        "charges": 0,
        "payment": "日结",
        "payment_channel": "在线支付",
        "job_walfare": {},
        "contactor": "孙小姐",
        "contactor_phone": "15210582639",
        "need_interview": 0,
        "is_agency": 0,
        "verify_status": 1,
        "update_time": "2015-07-01 09: 00: 00",
        "refresh_time": "2015-07-03 08: 00: 00",
        "position_source": "职位来源",
        "position_status": 1,
        "expire_date": "2015-09-01 00: 00: 00",
        "report_count": 1,
        "position_img": [
            "1.png",
            "2.png"
        ]
    }
}