{
    "code": 0,
    "message": "",
    "data": {
        "position_num": 2,
        "total_matched_num": 11,
        "current_page": 1,
        "positions": [
            {
                "position_title": "职位名称1",
                "position_id": "1",
                "post_time": "2015-09-01",
                "recruit_num": 80,
                "applied_num": 20,
                "payment": 1,
                "work_location": "理想大厦1层",
                "province": "北京",
                "city": "北京",
                "district": "海淀",
                "gender": 0,
                "curr_status": 1,
                "salary": 200,
                "salary_unit": "天",
                "num_new_messages": 2,
                "need_interview": 1,
                "is_agency": 0,
                "applied_users": 101,
                "accepted_cvs": 10,
                "interviewers": 30,
                "accepted_interviewers": 5,
                "interview_passed": 4,
                "offer_accepted": 2,
                "position_status": 0,
                "position_deny_reason": 1,
                "report_count": 0,
                "refresh_time": "2015-09-20",
                "thumbnail_img": "m.png"
            },
            {
                "position_title": "职位名称2",
                "position_id": "1",
                "post_time": "2015-09-01",
                "recruit_num": 80,
                "applied_num": 20,
                "payment": 1,
                "work_location": "理想大厦1层",
                "province": "北京",
                "city": "北京",
                "district": "海淀",
                "gender": 0,
                "curr_status": 1,
                "salary": 200,
                "salary_unit": "天",
                "num_new_messages": 2,
                "need_interview": 1,
                "is_agency": 0,
                "applied_users": 101,
                "accepted_cvs": 10,
                "interviewers": 30,
                "accepted_interviewers": 5,
                "interview_passed": 4,
                "offer_accepted": 2,
                "position_status": 0,
                "position_deny_reason": 1,
                "report_count": 0,
                "refresh_time": "2015-09-20",
                "thumbnail_img": "m.png"
            }
        ]
    }
}